# Generated by Django 5.1 on 2024-10-10 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_documentos_fecha_documentos_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialcambios',
            name='Version',
            field=models.DecimalField(blank=True, db_column='Version', decimal_places=4, max_digits=4, null=True),
        ),
    ]
