# Generated by Django 5.1 on 2024-10-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_historialcambios_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedimiento',
            name='Codigo',
            field=models.CharField(db_column='Codigo', max_length=500),
        ),
    ]
