# Generated by Django 5.1 on 2024-10-14 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_procedimiento_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedimiento',
            name='Diagrama_Flujo',
            field=models.CharField(blank=True, db_column='FirmaRevisado', max_length=50, null=True),
        ),
    ]
