# Generated by Django 5.1 on 2024-10-15 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_procedimiento_diagrama_flujo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedimiento',
            name='Diagrama_Flujo',
            field=models.ImageField(blank=True, db_column='Diagrama_Flujo', null=True, upload_to=''),
        ),
    ]
