# Generated by Django 5.1 on 2024-10-17 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_procedimiento_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=50, null=True)),
                ('Codigo', models.CharField(blank=True, db_column='Codigo', max_length=10, null=True)),
            ],
            options={
                'db_table': 'Departamento',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(blank=True, db_column='Descripcion', max_length=50, null=True)),
                ('Codificacion', models.CharField(blank=True, db_column='Codificacion', max_length=10, null=True)),
            ],
            options={
                'db_table': 'TipoDocumento',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='documentos',
            name='IDDepartamento',
            field=models.IntegerField(blank=True, db_column='IDDepartamento', null=True),
        ),
        migrations.AddField(
            model_name='documentos',
            name='IDTipoDocumento',
            field=models.IntegerField(blank=True, db_column='IDTipoDocumento', null=True),
        ),
        migrations.AddField(
            model_name='documentos',
            name='TipoDoc_Dep_Repr',
            field=models.CharField(blank=True, db_column='TipoDoc_Dep_Repr', max_length=100, null=True),
        ),
    ]
