# Generated by Django 5.1 on 2025-01-10 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_permisonivel_usuario_usuariocodigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdescripciones',
            name='Codigo',
            field=models.CharField(blank=True, db_column='Codigo', default='NA', max_length=50, null=True),
        ),
    ]
