# Generated by Django 5.1 on 2025-01-10 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_subdescripciones_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descripcionesprocedimiento',
            name='Codigo',
            field=models.CharField(blank=True, db_column='Codigo', default='NA', max_length=50, null=True),
        ),
    ]
