# Generated by Django 5.1 on 2025-01-28 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_descripcionesprocedimiento_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puestos',
            name='Actividad',
            field=models.CharField(blank=True, db_column='Actividad', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='puestos',
            name='UnidadNegocio',
            field=models.CharField(blank=True, db_column='UnidadNegocio', max_length=10, null=True),
        ),
    ]
