# Generated by Django 5.1 on 2025-02-05 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_puestos_actividad_alter_puestos_unidadnegocio'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadesPeriodicasPuesto',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('ActividadesDescri', models.CharField(blank=True, db_column='ActividadesDescri', max_length=500, null=True)),
                ('ResultadoFinalDescri', models.CharField(blank=True, db_column='ResultadoFinalDescri', max_length=500, null=True)),
                ('DescripcionPuesto', models.IntegerField(blank=True, db_column='DescripcionPuesto', null=True)),
            ],
            options={
                'db_table': 'ActividadesPeriodicasPuesto',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CompeteActituLista',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Descri', models.CharField(blank=True, db_column='Descri', max_length=300, null=True)),
                ('Indispensable', models.BooleanField(blank=True, db_column='Indispensable', default=False, null=True)),
                ('Deseable', models.BooleanField(blank=True, db_column='Deseable', default=False, null=True)),
                ('DescripcionPuesto', models.IntegerField(blank=True, db_column='DescripcionPuesto', null=True)),
            ],
            options={
                'db_table': 'CompeteActituLista',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CompeteTecniIndisLista',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Descri', models.CharField(blank=True, db_column='Descri', max_length=300, null=True)),
                ('BuenDominio', models.BooleanField(blank=True, db_column='BuenDominio', default=False, null=True)),
                ('DominioBasico', models.BooleanField(blank=True, db_column='DominioBasico', default=False, null=True)),
                ('DescripcionPuesto', models.IntegerField(blank=True, db_column='DescripcionPuesto', null=True)),
            ],
            options={
                'db_table': 'CompeteTecniIndisLista',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Computacion',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Descri', models.CharField(blank=True, db_column='Descri', max_length=300, null=True)),
                ('Grado', models.CharField(blank=True, db_column='Grado', max_length=10, null=True)),
                ('Indispensable', models.BooleanField(blank=True, db_column='Indispensable', default=False, null=True)),
                ('Deseable', models.BooleanField(blank=True, db_column='Deseable', default=False, null=True)),
                ('DescripcionPuesto', models.IntegerField(blank=True, db_column='DescripcionPuesto', null=True)),
            ],
            options={
                'db_table': 'Computacion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CondicionesFisicas',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Descri', models.CharField(blank=True, db_column='Descri', max_length=300, null=True)),
                ('DescripcionPuesto', models.IntegerField(blank=True, db_column='DescripcionPuesto', null=True)),
            ],
            options={
                'db_table': 'CondicionesFisicas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DecisionesSinAprobacion',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Descri', models.CharField(blank=True, db_column='Descri', max_length=500, null=True)),
                ('DescripcionPuesto', models.IntegerField(blank=True, db_column='DescripcionPuesto', null=True)),
            ],
            options={
                'db_table': 'DecisionesSinAprobacion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DescripcionPuesto',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('CodigoPuesto', models.IntegerField(blank=True, db_column='CodigoPuesto', null=True)),
                ('TituloPuesto', models.IntegerField(blank=True, db_column='TituloPuesto', null=True)),
                ('ReportaA', models.IntegerField(blank=True, db_column='ReportaA', null=True)),
                ('Departamento', models.IntegerField(blank=True, db_column='Departamento', null=True)),
                ('CodigoDepartamento', models.CharField(blank=True, db_column='CodigoDepartamento', max_length=50, null=True)),
                ('Ubicacion', models.CharField(blank=True, db_column='Ubicacion', max_length=50, null=True)),
                ('ObjetivoPuesto', models.CharField(blank=True, db_column='ObjetivoPuesto', max_length=500, null=True)),
                ('OrganigramaDescri', models.CharField(blank=True, db_column='OrganigramaDescri', max_length=500, null=True)),
                ('OrganigramaFile', models.BinaryField(blank=True, db_column='OrganigramaFile', null=True)),
                ('CompeteActituDescr', models.CharField(blank=True, db_column='CompeteActituDescr', max_length=500, null=True)),
                ('CompeteTecniIndisDescr', models.CharField(blank=True, db_column='CompeteTecniIndisDescr', max_length=500, null=True)),
            ],
            options={
                'db_table': 'DescripcionPuesto',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ExperienciaIdeal',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Descri', models.CharField(blank=True, db_column='Descri', max_length=300, null=True)),
                ('Indispensable', models.BooleanField(blank=True, db_column='Indispensable', default=False, null=True)),
                ('Deseable', models.BooleanField(blank=True, db_column='Deseable', default=False, null=True)),
                ('DescripcionPuesto', models.IntegerField(blank=True, db_column='DescripcionPuesto', null=True)),
            ],
            options={
                'db_table': 'ExperienciaIdeal',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FormacionAcademica',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Descri', models.CharField(blank=True, db_column='Descri', max_length=300, null=True)),
                ('Indispensable', models.BooleanField(blank=True, db_column='Indispensable', default=False, null=True)),
                ('Deseable', models.BooleanField(blank=True, db_column='Deseable', default=False, null=True)),
                ('DescripcionPuesto', models.IntegerField(blank=True, db_column='DescripcionPuesto', null=True)),
            ],
            options={
                'db_table': 'FormacionAcademica',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FuncionesPuesto',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('FuncionesDescri', models.CharField(blank=True, db_column='FuncionesDescri', max_length=500, null=True)),
                ('ResultadoFinalDescri', models.CharField(blank=True, db_column='ResultadoFinalDescri', max_length=500, null=True)),
                ('DescripcionPuesto', models.IntegerField(blank=True, db_column='DescripcionPuesto', null=True)),
            ],
            options={
                'db_table': 'FuncionesPuesto',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='GradoAutoridadDecisiones',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Descri', models.CharField(blank=True, db_column='Descri', max_length=500, null=True)),
                ('DescripcionPuesto', models.IntegerField(blank=True, db_column='DescripcionPuesto', null=True)),
            ],
            options={
                'db_table': 'GradoAutoridadDecisiones',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Idiomas',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Descri', models.CharField(blank=True, db_column='Descri', max_length=300, null=True)),
                ('DescripcionPuesto', models.IntegerField(blank=True, db_column='DescripcionPuesto', null=True)),
            ],
            options={
                'db_table': 'Idiomas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='IdiomasHabilidades',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Descri', models.CharField(blank=True, db_column='Descri', max_length=50, null=True)),
                ('Grado', models.CharField(blank=True, db_column='Grado', max_length=10, null=True)),
                ('Indispensable', models.BooleanField(blank=True, db_column='Indispensable', default=False, null=True)),
                ('Deseable', models.BooleanField(blank=True, db_column='Deseable', default=False, null=True)),
                ('Idiomas', models.IntegerField(blank=True, db_column='Idiomas', null=True)),
            ],
            options={
                'db_table': 'IdiomasHabilidades',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RelacionesExternas',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Puesto', models.IntegerField(blank=True, db_column='Puesto', null=True)),
                ('Descri', models.CharField(blank=True, db_column='Descri', max_length=500, null=True)),
                ('DescripcionPuesto', models.IntegerField(blank=True, db_column='DescripcionPuesto', null=True)),
            ],
            options={
                'db_table': 'RelacionesExternas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RelacionesInternas',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Puesto', models.IntegerField(blank=True, db_column='Puesto', null=True)),
                ('Descri', models.CharField(blank=True, db_column='Descri', max_length=500, null=True)),
                ('DescripcionPuesto', models.IntegerField(blank=True, db_column='DescripcionPuesto', null=True)),
            ],
            options={
                'db_table': 'RelacionesInternas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ResponRecurYMateriales',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Descri', models.CharField(blank=True, db_column='Descri', max_length=500, null=True)),
                ('DescripcionPuesto', models.IntegerField(blank=True, db_column='DescripcionPuesto', null=True)),
            ],
            options={
                'db_table': 'ResponRecurYMateriales',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Riesgos',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Descri', models.CharField(blank=True, db_column='Descri', max_length=300, null=True)),
                ('DescripcionPuesto', models.IntegerField(blank=True, db_column='DescripcionPuesto', null=True)),
            ],
            options={
                'db_table': 'Riesgos',
                'managed': True,
            },
        ),
    ]
