# Generated by Django 5.1 on 2025-03-06 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_actividadesperiodicaspuesto_competeactitulista_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoundManual',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Codigo', models.CharField(blank=True, db_column='Codigo', max_length=200, null=True)),
                ('Descri', models.CharField(blank=True, db_column='Descri', max_length=500, null=True)),
                ('Manual', models.IntegerField(blank=True, db_column='Manual', null=True)),
            ],
            options={
                'db_table': 'BoundManual',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BoundProcedimiento',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Codigo', models.CharField(blank=True, db_column='Codigo', max_length=200, null=True)),
                ('Descri', models.CharField(blank=True, db_column='Descri', max_length=500, null=True)),
                ('Manual', models.IntegerField(blank=True, db_column='Manual', null=True)),
            ],
            options={
                'db_table': 'BoundProcedimiento',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CategorizacionGasto',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Descri', models.CharField(blank=True, db_column='Descri', max_length=500, null=True)),
                ('Sigla', models.CharField(blank=True, db_column='Sigla', max_length=50, null=True)),
                ('Manual', models.IntegerField(blank=True, db_column='Manual', null=True)),
            ],
            options={
                'db_table': 'CategorizacionGasto',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CategorizacionGastoPartida',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Descri', models.CharField(blank=True, db_column='Descri', max_length=500, null=True)),
                ('Sigla', models.CharField(blank=True, db_column='Sigla', max_length=50, null=True)),
                ('CategorizacionGasto', models.IntegerField(blank=True, db_column='CategorizacionGasto', null=True)),
                ('Manual', models.IntegerField(blank=True, db_column='Manual', null=True)),
            ],
            options={
                'db_table': 'CategorizacionGastoPartida',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ClienteExterno',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Cliente', models.CharField(blank=True, db_column='Cliente', max_length=200, null=True)),
                ('Necesidad', models.CharField(blank=True, db_column='Necesidad', max_length=800, null=True)),
                ('Expectativa', models.CharField(blank=True, db_column='Expectativa', max_length=800, null=True)),
                ('Manual', models.IntegerField(blank=True, db_column='Manual', null=True)),
            ],
            options={
                'db_table': 'ClienteExterno',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ClienteInterno',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Cliente', models.CharField(blank=True, db_column='Cliente', max_length=200, null=True)),
                ('Necesidad', models.CharField(blank=True, db_column='Necesidad', max_length=800, null=True)),
                ('Expectativa', models.CharField(blank=True, db_column='Expectativa', max_length=800, null=True)),
                ('Manual', models.IntegerField(blank=True, db_column='Manual', null=True)),
            ],
            options={
                'db_table': 'ClienteInterno',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ComunicacionExterna',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('TipoComunicacion', models.CharField(blank=True, db_column='TipoComunicacion', max_length=500, null=True)),
                ('Periodicidad', models.CharField(blank=True, db_column='Periodicidad', max_length=500, null=True)),
                ('Manual', models.IntegerField(blank=True, db_column='Manual', null=True)),
            ],
            options={
                'db_table': 'ComunicacionExterna',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ComunicacionInterna',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('TipoComunicacion', models.CharField(blank=True, db_column='TipoComunicacion', max_length=500, null=True)),
                ('Periodicidad', models.CharField(blank=True, db_column='Periodicidad', max_length=500, null=True)),
                ('Manual', models.IntegerField(blank=True, db_column='Manual', null=True)),
            ],
            options={
                'db_table': 'ComunicacionInterna',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DescripcionPuestoManual',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Codigo', models.CharField(blank=True, db_column='Codigo', max_length=200, null=True)),
                ('Descri', models.CharField(blank=True, db_column='Descri', max_length=500, null=True)),
                ('Manual', models.IntegerField(blank=True, db_column='Manual', null=True)),
            ],
            options={
                'db_table': 'DescripcionPuestoManual',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Manual',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('CodigoManual', models.IntegerField(blank=True, db_column='CodigoManual', null=True)),
                ('ObjetivoGeneralManualDescri', models.CharField(blank=True, db_column='ObjetivoGeneralManualDescri', max_length=500, null=True)),
                ('ObjetivoEspecificoManualDescri', models.CharField(blank=True, db_column='ObjetivoEspecificoManualDescri', max_length=500, null=True)),
                ('AlcanceDescri', models.CharField(blank=True, db_column='AlcanceDescri', max_length=300, null=True)),
                ('ObjetivoGeneralUnidadNegocio', models.CharField(blank=True, db_column='ObjetivoGeneralUnidadNegocio', max_length=500, null=True)),
                ('MapaProcesoDescri', models.CharField(blank=True, db_column='MapaProcesoDescri', max_length=500, null=True)),
                ('MapaProcesoFile', models.BinaryField(blank=True, db_column='MapaProcesoFile', null=True)),
                ('EstructuraProcesoDescri', models.CharField(blank=True, db_column='EstructuraProcesoDescri', max_length=500, null=True)),
                ('EstructuraProcesoFile', models.BinaryField(blank=True, db_column='EstructuraProcesoFile', null=True)),
                ('OrganigramaEstructuralDescri', models.CharField(blank=True, db_column='OrganigramaEstructuralDescri', max_length=500, null=True)),
                ('OrganigramaEstructuralFile', models.BinaryField(blank=True, db_column='OrganigramaEstructuralFile', null=True)),
                ('OrganigramaFuncionalDescri', models.CharField(blank=True, db_column='OrganigramaFuncionalDescri', max_length=500, null=True)),
                ('OrganigramaFuncionalFile', models.BinaryField(blank=True, db_column='OrganigramaFuncionalFile', null=True)),
                ('PresupuestoDescri', models.CharField(blank=True, db_column='PresupuestoDescri', max_length=800, null=True)),
                ('PresupuestoSecondDescri', models.CharField(blank=True, db_column='PresupuestoSecondDescri', max_length=800, null=True)),
                ('RendicionCuentaDescri', models.CharField(blank=True, db_column='RendicionCuentaDescri', max_length=800, null=True)),
                ('IndicadorProcesoGestion', models.BinaryField(blank=True, db_column='IndicadorProcesoGestion', null=True)),
                ('IndicadorProcesoGestionRiesgoDescri', models.CharField(blank=True, db_column='IndicadorProcesoGestionRiesgoDescri', max_length=800, null=True)),
                ('IndicadorProcesoGestionRiesgoFile', models.BinaryField(blank=True, db_column='IndicadorProcesoGestionRiesgoFile', null=True)),
            ],
            options={
                'db_table': 'Manual',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MarcoLegal',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Descri', models.CharField(blank=True, db_column='Descri', max_length=500, null=True)),
                ('Manual', models.IntegerField(blank=True, db_column='Manual', null=True)),
            ],
            options={
                'db_table': 'MarcoLegal',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ObjetivoEspecificoManualLista',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Descri', models.CharField(blank=True, db_column='Descri', max_length=500, null=True)),
                ('Manual', models.IntegerField(blank=True, db_column='Manual', null=True)),
            ],
            options={
                'db_table': 'ObjetivoEspecificoManualLista',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ObjetivoEspecificoUnidadNegocio',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Descri', models.CharField(blank=True, db_column='Descri', max_length=500, null=True)),
                ('Manual', models.IntegerField(blank=True, db_column='Manual', null=True)),
            ],
            options={
                'db_table': 'ObjetivoEspecificoUnidadNegocio',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RendicionCuentaLista',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Descri', models.CharField(blank=True, db_column='Descri', max_length=500, null=True)),
                ('Manual', models.IntegerField(blank=True, db_column='Manual', null=True)),
            ],
            options={
                'db_table': 'RendicionCuentaLista',
                'managed': True,
            },
        ),
    ]
