# Generated by Django 5.1 on 2025-04-11 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_boundmanual_boundprocedimiento_categorizaciongasto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnexoPolitica',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Codigo', models.CharField(blank=True, db_column='Codigo', max_length=50, null=True)),
                ('Descri', models.CharField(blank=True, db_column='Descri', max_length=500, null=True)),
                ('Politica', models.IntegerField(blank=True, db_column='Politica', null=True)),
            ],
            options={
                'db_table': 'AnexoPolitica',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BoundProveedoresPolitica',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Codigo', models.CharField(blank=True, db_column='Codigo', max_length=50, null=True)),
                ('Descri', models.CharField(blank=True, db_column='Descri', max_length=500, null=True)),
                ('Politica', models.IntegerField(blank=True, db_column='Politica', null=True)),
            ],
            options={
                'db_table': 'BoundProveedoresPolitica',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ClasificacionTipoMaterialPolitica',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Categoria', models.CharField(blank=True, db_column='Categoria', max_length=50, null=True)),
                ('Descri', models.CharField(blank=True, db_column='Descri', max_length=500, null=True)),
                ('Politica', models.IntegerField(blank=True, db_column='Politica', null=True)),
            ],
            options={
                'db_table': 'ClasificacionTipoMaterialPolitica',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Politica',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('CodigoPolitica', models.IntegerField(blank=True, db_column='CodigoManual', null=True)),
                ('ObjetivoDescri', models.CharField(blank=True, db_column='ObjetivoDescri', max_length=500, null=True)),
                ('AlcanceDescri', models.CharField(blank=True, db_column='AlcanceDescri', max_length=500, null=True)),
                ('PrecioCompra', models.CharField(blank=True, db_column='PrecioCompra', max_length=500, null=True)),
                ('HorarioRecibo', models.CharField(blank=True, db_column='HorarioRecibo', max_length=500, null=True)),
                ('ProveedoresDescri', models.CharField(blank=True, db_column='ProveedoresDescri', max_length=500, null=True)),
                ('Pago', models.CharField(blank=True, db_column='Pago', max_length=500, null=True)),
            ],
            options={
                'db_table': 'Politica',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ResponsabilidadesPolitica',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Indice', models.CharField(blank=True, db_column='Indice', max_length=10, null=True)),
                ('Descri', models.CharField(blank=True, db_column='Descri', max_length=500, null=True)),
                ('Puesto', models.IntegerField(blank=True, db_column='Puesto', null=True)),
                ('Politica', models.IntegerField(blank=True, db_column='Politica', null=True)),
            ],
            options={
                'db_table': 'ResponsabilidadesPolitica',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TerminologiasPolitica',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Descri', models.CharField(blank=True, db_column='Descri', max_length=500, null=True)),
                ('Termino', models.IntegerField(blank=True, db_column='Termino', null=True)),
                ('Politica', models.IntegerField(blank=True, db_column='Politica', null=True)),
            ],
            options={
                'db_table': 'TerminologiasPolitica',
                'managed': True,
            },
        ),
    ]
