# Generated by Django 5.1 on 2025-04-12 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_documentosreferenciaspolitica'),
    ]

    operations = [
        migrations.AddField(
            model_name='politica',
            name='ClasificacionPoliticaDescri',
            field=models.CharField(blank=True, db_column='ClasificacionPoliticaDescri', max_length=500, null=True),
        ),
    ]
