# Generated by Django 5.1 on 2025-04-13 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_politica_clasificacionpoliticadescri'),
    ]

    operations = [
        migrations.AddField(
            model_name='anexopolitica',
            name='Numero',
            field=models.CharField(blank=True, db_column='Numero', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clasificaciontipomaterialpolitica',
            name='TipoMaterial',
            field=models.IntegerField(blank=True, db_column='TipoMaterial', null=True),
        ),
    ]
