# Generated by Django 5.1 on 2025-04-13 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_anexopolitica_numero_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='politica',
            name='Pago',
        ),
        migrations.AddField(
            model_name='politica',
            name='PagoDescri',
            field=models.CharField(blank=True, db_column='PagoDescri', max_length=500, null=True),
        ),
    ]
