# Generated by Django 5.1 on 2025-04-13 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_politica_pago_politica_pagodescri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clasificaciontipomaterialpolitica',
            name='TipoMaterial',
            field=models.CharField(blank=True, db_column='TipoMaterial', null=True),
        ),
    ]
