# Generated by Django 5.1 on 2025-04-14 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_clasificaciontipomaterialpolitica_tipomaterial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TerminologiasDefPolitica',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('IDTermino', models.IntegerField(db_column='IDTermino')),
                ('Descripcion', models.CharField(db_column='Descripcion', max_length=500)),
                ('Politica', models.IntegerField(db_column='Politica')),
            ],
            options={
                'db_table': 'TerminologiasDefPolitica',
                'managed': True,
            },
        ),
    ]
