# Generated by Django 5.1 on 2025-04-14 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_terminologiasdefpolitica'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BoundProveedoresPolitica',
            new_name='BoundProcedimientosPolitica',
        ),
        migrations.AlterModelTable(
            name='boundprocedimientospolitica',
            table='BoundProcedimientosPolitica',
        ),
    ]
