# Generated by Django 5.1 on 2025-04-15 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_rename_boundproveedorespolitica_boundprocedimientospolitica_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politica',
            name='CodigoPolitica',
            field=models.IntegerField(blank=True, db_column='CodigoPolitica', null=True),
        ),
    ]
