# Generated by Django 5.1 on 2025-04-25 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_politica_codigopolitica'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructivo',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('CodigoInstructivo', models.IntegerField(blank=True, db_column='CodigoInstructivo', null=True)),
                ('ObjetivoDescri', models.CharField(blank=True, db_column='ObjetivoDescri', max_length=500, null=True)),
                ('AlcanceDescri', models.CharField(blank=True, db_column='AlcanceDescri', max_length=500, null=True)),
            ],
            options={
                'db_table': 'Instructivo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InstructivoAnexo',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Numero', models.CharField(blank=True, db_column='Numero', max_length=50, null=True)),
                ('Descri', models.CharField(blank=True, db_column='Descri', max_length=500, null=True)),
                ('Codigo', models.CharField(blank=True, db_column='Codigo', max_length=50, null=True)),
                ('Instructivo', models.IntegerField(blank=True, db_column='Instructivo', null=True)),
            ],
            options={
                'db_table': 'InstructivoAnexo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InstructivoInstrucciones',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Indice', models.CharField(blank=True, db_column='Indice', max_length=10, null=True)),
                ('Descri', models.CharField(blank=True, db_column='Descri', max_length=500, null=True)),
                ('Instructivo', models.IntegerField(blank=True, db_column='Instructivo', null=True)),
            ],
            options={
                'db_table': 'InstructivoInstrucciones',
                'managed': True,
            },
        ),
    ]
