# Generated by Django 5.1 on 2025-05-02 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_clasificaciontipomaterialpolitica_tipopolitica'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clasificaciontipomaterialpolitica',
            name='TipoPolitica',
        ),
        migrations.AddField(
            model_name='clasificaciontipomaterialpolitica',
            name='TipoPoliticaFile',
            field=models.BinaryField(blank=True, db_column='TipoPoliticaFile', null=True),
        ),
    ]
