# Generated by Django 5.1 on 2025-05-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_remove_clasificaciontipomaterialpolitica_tipopolitica_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clasificaciontipomaterialpolitica',
            name='TipoPoliticaFile',
        ),
        migrations.AddField(
            model_name='politica',
            name='TipoPoliticaFile',
            field=models.BinaryField(blank=True, db_column='TipoPoliticaFile', null=True),
        ),
    ]
