# Generated by Django 5.1 on 2025-05-07 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_remove_revaprobacion_idprocedimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revaprobacion',
            name='FirmaAprobado',
            field=models.BinaryField(blank=True, db_column='FirmaAprobado', null=True),
        ),
        migrations.AlterField(
            model_name='revaprobacion',
            name='FirmaElaborado',
            field=models.BinaryField(blank=True, db_column='FirmaElaborado', null=True),
        ),
        migrations.AlterField(
            model_name='revaprobacion',
            name='FirmaRevisado',
            field=models.BinaryField(blank=True, db_column='FirmaRevisado', null=True),
        ),
    ]
