# Generated by Django 5.1 on 2025-05-08 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_alter_revaprobacion_firmaaprobado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialcambios',
            name='IDProcedimiento',
        ),
        migrations.AddField(
            model_name='historialcambios',
            name='DocumentKey',
            field=models.CharField(blank=True, db_column='DocumentKey', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='historialcambios',
            name='FormName',
            field=models.CharField(blank=True, db_column='FormName', max_length=50, null=True),
        ),
    ]
