# Generated by Django 5.1 on 2025-05-08 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_remove_historialcambios_idprocedimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialcambios',
            name='Descripcion',
            field=models.CharField(blank=True, db_column='Descripcion', max_length=9999, null=True),
        ),
    ]
